language: ruby

arch: 
  - amd64
  - ppc64le   

addons:
   apt:
    update: true
    packages: ant make wget unzip tar gcc ruby


install:
   - gem install rake
   - gem install bundler

script:
   - rake bootstrap
   - rake plugin:install-default
